version: "3.8"
services:
  nginx:
    container_name: nginx-chop-chop
    restart: unless-stopped
    build:
      context: ./nginx/
    ports:
      - $NGINX_PORT:80
    volumes:
      - "./frontend/dist:/usr/share/nginx/html"
  frontend:
    container_name: frontend-chop-chop-$BUILD_TYPE
    restart: no
    build:
      context: ./frontend/
      target: $BUILD_TYPE
    volumes:
      - ./frontend/src:/usr/chop-chop/src
      - ./frontend/dist:/usr/chop-chop/dist
